//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInfoEx3AConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.AssignmentGrades = new HashSet<AssignmentGrade>();
        }
    
        public int Id { get; set; }
        public string Assign { get; set; }
        public string Description { get; set; }
        public short MaxPoints { get; set; }
        public System.DateTime DueDate { get; set; }

        private readonly AssignmentTypesEnum AssignmentTypeEnum;

        public AssignmentTypesEnum Type { get; set; }
    
        public virtual Section Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentGrade> AssignmentGrades { get; set; }
    }
}
