//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInfo3B
{
    using System;
    
    public enum GradesEnum : int
    {
        A = 0,
        B = 1,
        C = 2,
        D = 3,
        F = 4,
        P = 5,
        NC = 6,
        W = 7,
        AU = 8,
        I = 9,
        IP = 10,
        Z = 11
    }
}
