//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInfo3B
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentInfoModelContainer : DbContext
    {
        public StudentInfoModelContainer()
            : base("name=StudentInfoModelContainer")
        {
            this.Configuration.LazyLoadingEnabled = false;
            Database.SetInitializer<StudentInfoModelContainer>(new StudentInfoDBInitializer());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<AssignmentGrade> AssignmentGrades { get; set; }
    }
}
