//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInfo3B
{
    using System;
    
    public enum TermsEnum : int
    {
        Fall = 0,
        Spr = 1,
        Sum = 2
    }
}
